"""Added broadcast channel, delete votes

Revision ID: 0e90a7a744ed
Revises: 06b3d18f24b9
Create Date: 2024-04-22 23:03:12.468479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e90a7a744ed'
down_revision: Union[str, None] = '06b3d18f24b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.add_column('guild', sa.Column('broadcast_channel_id', sa.String(), nullable=True))
    op.alter_column('guild', 'brancoins',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guild', 'brancoins',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.drop_column('guild', 'broadcast_channel_id')
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_league_player', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_of_vote', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['target_league_player'], ['league_user.id'], name='votes_target_league_player_fkey'),
    sa.ForeignKeyConstraint(['voter'], ['user_account.id'], name='votes_voter_fkey'),
    sa.PrimaryKeyConstraint('id', name='votes_pkey'),
    sa.UniqueConstraint('id', name='votes_id_key')
    )
    # ### end Alembic commands ###
