"""empty message

Revision ID: 119a402d17cf
Revises: 
Create Date: 2024-05-20 17:38:47.209151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119a402d17cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('bin', sa.LargeBinary(length=4294967295), nullable=True),
    sa.PrimaryKeyConstraint('label'),
    sa.UniqueConstraint('label')
    )
    op.create_table('booster_pack',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('image_label', sa.String(length=32), nullable=False),
    sa.Column('desc', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['image_label'], ['images.label'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_style', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('attribute', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=32), nullable=False),
    sa.Column('atk', sa.String(length=32), nullable=False),
    sa.Column('defe', sa.String(length=32), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('image_label', sa.String(length=32), nullable=False),
    sa.Column('shoppable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image_label'], ['images.label'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('booster_segments',
    sa.Column('booster_pack_id', sa.String(length=32), nullable=False),
    sa.Column('num_cards_to_draw', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('bg_fname', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['booster_pack_id'], ['booster_pack.id'], ),
    sa.PrimaryKeyConstraint('booster_pack_id', 'id')
    )
    op.create_table('booster_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('booster_pack_id', sa.String(length=32), nullable=False),
    sa.Column('booster_segment_id', sa.String(length=32), nullable=False),
    sa.Column('chance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['booster_pack_id', 'booster_segment_id'], ['booster_segments.booster_pack_id', 'booster_segments.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booster_card')
    op.drop_table('booster_segments')
    op.drop_table('cards')
    op.drop_table('booster_pack')
    op.drop_table('images')
    # ### end Alembic commands ###
