"""empty message

Revision ID: 187d59df5391
Revises: e1e419059f3f
Create Date: 2024-05-18 05:43:41.734940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187d59df5391'
down_revision: Union[str, None] = 'e1e419059f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('featured', sa.Boolean(), server_default='False', nullable=False))
    op.drop_column('shop', 'featured')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('cards', 'featured')
    # ### end Alembic commands ###
