"""Recreated votes

Revision ID: 1aaddc89b9cf
Revises: 0e90a7a744ed
Create Date: 2024-04-22 23:03:35.340631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaddc89b9cf'
down_revision: Union[str, None] = '0e90a7a744ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voter', sa.Integer(), nullable=False),
    sa.Column('target_league_player', sa.Integer(), nullable=True),
    sa.Column('type_of_vote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_league_player'], ['league_user.id'], ),
    sa.ForeignKeyConstraint(['voter'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
