"""Updated votes schema

Revision ID: 45ade50185ad
Revises: 1aaddc89b9cf
Create Date: 2024-04-23 03:06:36.485588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ade50185ad'
down_revision: Union[str, None] = '1aaddc89b9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('voter_id', sa.Integer(), nullable=False))
    op.add_column('votes', sa.Column('match_id', sa.String(), nullable=False))
    op.add_column('votes', sa.Column('brancoins', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'votes', ['id'])
    op.drop_constraint('votes_voter_fkey', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'user_account', ['voter_id'], ['id'])
    op.create_foreign_key(None, 'votes', 'match', ['match_id'], ['match_id'])
    op.drop_column('votes', 'voter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('voter', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_voter_fkey', 'votes', 'user_account', ['voter'], ['id'])
    op.drop_constraint(None, 'votes', type_='unique')
    op.drop_column('votes', 'brancoins')
    op.drop_column('votes', 'match_id')
    op.drop_column('votes', 'voter_id')
    # ### end Alembic commands ###
