"""added match user

Revision ID: 535e54884892
Revises: a84eca85e774
Create Date: 2024-04-20 22:28:38.329432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535e54884892'
down_revision: Union[str, None] = 'a84eca85e774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_player',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('league_user_id', sa.Integer(), nullable=False),
    sa.Column('champion', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_user_id'], ['league_user.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ),
    sa.PrimaryKeyConstraint('match_id', 'league_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_player')
    # ### end Alembic commands ###
