"""added images

Revision ID: 6222aa1312b6
Revises: c6d91231612f
Create Date: 2024-05-17 00:27:55.754940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6222aa1312b6'
down_revision: Union[str, None] = 'c6d91231612f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('bin', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('label'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
