"""Establish user and leagueuser relationship

Revision ID: 7b99816729d1
Revises: 8c9e4b3dc8ba
Create Date: 2024-04-19 01:07:07.532077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b99816729d1'
down_revision: Union[str, None] = '8c9e4b3dc8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_user', sa.Column('discord_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'league_user', 'user_account', ['discord_user_id'], ['id'])
    op.drop_constraint('user_account_league_user_id_fkey', 'user_account', type_='foreignkey')
    op.drop_column('user_account', 'league_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('league_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_account_league_user_id_fkey', 'user_account', 'league_user', ['league_user_id'], ['id'])
    op.drop_constraint(None, 'league_user', type_='foreignkey')
    op.drop_column('league_user', 'discord_user_id')
    # ### end Alembic commands ###
