"""Updated votes, added processed

Revision ID: 7ea3539106b7
Revises: 45ade50185ad
Create Date: 2024-04-23 04:45:42.530612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea3539106b7'
down_revision: Union[str, None] = '45ade50185ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('processed', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'processed')
    # ### end Alembic commands ###
