"""tag

Revision ID: 8a7c3ea56cdb
Revises: fc16e8de4735
Create Date: 2024-04-20 23:26:49.602970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7c3ea56cdb'
down_revision: Union[str, None] = 'fc16e8de4735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'jackpot', ['guild_id'])
    op.add_column('league_user', sa.Column('tag', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_user', 'tag')
    op.drop_constraint(None, 'jackpot', type_='unique')
    # ### end Alembic commands ###
