"""Adding uniquess for user and guild in discord user table

Revision ID: 8c9e4b3dc8ba
Revises: ca28184411ec
Create Date: 2024-04-18 04:07:53.494561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9e4b3dc8ba'
down_revision: Union[str, None] = 'ca28184411ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_guild_uc', 'user_account', ['user_id', 'guild_id'])
    op.create_unique_constraint(None, 'user_account', ['id'])
    op.create_unique_constraint(None, 'votes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='unique')
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_constraint('user_guild_uc', 'user_account', type_='unique')
    # ### end Alembic commands ###
