"""Adding card table

Revision ID: a52aa5f1ab78
Revises: 6222aa1312b6
Create Date: 2024-05-17 02:26:08.227002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52aa5f1ab78'
down_revision: Union[str, None] = '6222aa1312b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_style', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('atk', sa.String(), nullable=False),
    sa.Column('defe', sa.String(), nullable=False),
    sa.Column('image_label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['image_label'], ['images.label'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'images', ['label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_table('cards')
    # ### end Alembic commands ###
