"""jackpot

Revision ID: a84eca85e774
Revises: bdf5fb01b6fa
Create Date: 2024-04-20 21:56:21.342097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84eca85e774'
down_revision: Union[str, None] = 'bdf5fb01b6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jackpot',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('brancoins', sa.Integer(), server_default='10', nullable=True),
    sa.PrimaryKeyConstraint('guild_id'),
    sa.UniqueConstraint('guild_id')
    )
    op.add_column('match', sa.Column('finished', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('match', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('match', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('match', 'start_time')
    op.drop_column('match', 'finished')
    op.drop_table('jackpot')
    # ### end Alembic commands ###
