"""segment bgs

Revision ID: aa0f6aad0d10
Revises: 115ddf43f463
Create Date: 2024-05-18 18:59:42.483114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0f6aad0d10'
down_revision: Union[str, None] = '115ddf43f463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booster_segments', sa.Column('bg_fname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booster_segments', 'bg_fname')
    # ### end Alembic commands ###
