"""empty message

Revision ID: b725cef0d49d
Revises: 05aac18d388b
Create Date: 2024-05-18 06:05:43.758715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b725cef0d49d'
down_revision: Union[str, None] = '05aac18d388b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('shoppable', sa.Boolean(), server_default='t', nullable=False))
    op.add_column('cards', sa.Column('featured', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'featured')
    op.drop_column('cards', 'shoppable')
    # ### end Alembic commands ###
