"""fixed league table

Revision ID: bdf5fb01b6fa
Revises: 7b99816729d1
Create Date: 2024-04-20 18:04:44.278037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf5fb01b6fa'
down_revision: Union[str, None] = '7b99816729d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_user', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_user', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
