"""broadcast role

Revision ID: c6d91231612f
Revises: 7ea3539106b7
Create Date: 2024-04-23 21:50:53.507875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d91231612f'
down_revision: Union[str, None] = '7ea3539106b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('broadcast_role_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild', 'broadcast_role_id')
    # ### end Alembic commands ###
