"""Creating migration

Revision ID: ca28184411ec
Revises: 
Create Date: 2024-04-18 03:57:02.876843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca28184411ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summoner_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('trackable', sa.Boolean(), nullable=False),
    sa.Column('voteable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'summoner_name', 'region'),
    sa.UniqueConstraint('id')
    )
    op.create_table('match',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_user_id', sa.Integer(), nullable=True),
    sa.Column('brancoins', sa.Integer(), server_default='10', nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_user_id'], ['league_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voter', sa.Integer(), nullable=False),
    sa.Column('target_league_player', sa.Integer(), nullable=False),
    sa.Column('type_of_vote', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['target_league_player'], ['league_user.id'], ),
    sa.ForeignKeyConstraint(['voter'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('user_account')
    op.drop_table('match')
    op.drop_table('league_user')
    # ### end Alembic commands ###
