"""Remove uc

Revision ID: ccff6feeb9b3
Revises: aa0f6aad0d10
Create Date: 2024-05-18 21:28:21.588425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccff6feeb9b3'
down_revision: Union[str, None] = 'aa0f6aad0d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_title_key', 'cards', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cards_title_key', 'cards', ['title'])
    # ### end Alembic commands ###
