"""added shoppable cards

Revision ID: e1e419059f3f
Revises: e7d8c49f50c8
Create Date: 2024-05-18 05:29:37.216395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e419059f3f'
down_revision: Union[str, None] = 'e7d8c49f50c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('shoppable', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'shoppable')
    # ### end Alembic commands ###
